service:
  name: hello-world

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  createAuction:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: hello-world
